services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: supplychain-mssql
    restart: always
    environment:
      SA_PASSWORD: "Scsql123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: supplychain-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mssql_data:
  redis_data:
